import Head from "next/head";
import styles from "../styles/Home.module.css";
import useLocalStorageState from "use-local-storage-state";

export default function Home() {
  const [chatHistory, setChatHistory] = useLocalStorageState("history", {
    defaultValue: [],
  });

  function handleReset() {
    setChatHistory([]);
  }

  async function handleSubmit(event) {
    event.preventDefault();

    const query = event.target.query.value;
    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          chatHistory,
          query,
        }),
      });
      const data = await response.json();
      setChatHistory((prev) => [
        ...prev,
        {
          id: crypto.randomUUID(),
          role: "user",
          content: query,
        },
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: data.content,
        },
      ]);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>fishGPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>fishGPT - go with the flow!</h1>
      <form action="" onSubmit={handleSubmit}>
        <button type="button" onClick={handleReset}>
          reset
        </button>
        <input name="query" type="text" placeholder="ask chatGPT something" />
        <button type="submit">go</button>
      </form>
      <ul>
        {chatHistory.map((message) => (
          <li key={message.id} className={styles.message}>
            {message.content}
          </li>
        ))}
      </ul>
    </div>
  );
}
